/////////////////////////////////////////////////////////////////////////////
//
// Icons
//

/////////////////////////////////////////////////////////////////////////////
//
// Menus
//

#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_ACTIVE_MODEL_CONFIGURATION									12265
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_SINGLE														12266
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_2_VERTICAL													12270
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_2_HORIZONTAL												12280
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_3_RIGHT														12290
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_3_LEFT														12300
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_3_ABOVE														12310
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_3_BELOW														12320
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_3_VERTICAL													12330
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_3_HORIZONTAL												12340
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_4_EQUAL														12350
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_4_RIGHT														12360
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_4_LEFT														12370

#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_CONTEXT_DISPLAY												25300
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_CONTEXT_CURRENTVIEWPORT										25310

#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_SETUP_2D													25400
#define ID_VIEW_VIEWPORTS_NEW_VIEWPORTS_SETUP_3D													25410

#define ID_TOOLS_DRAFTINGSETTINGS_OPTIONS															30060

/////////////////////////////////////////////////////////////////////////////
//
// Accelerators
//

/////////////////////////////////////////////////////////////////////////////
//
// Dialogs
//

#define IDD_DRAFTINGSETTINGS																		200
#define IDD_DRAFTINGSETTINGS_SNAPANDGRID															210
#define IDD_DRAFTINGSETTINGS_POLARTRACKING															220
#define IDD_DRAFTINGSETTINGS_OBJECTSNAP																230
#define IDD_DRAFTINGSETTINGS_3DOBJECTSNAP															240
#define IDD_DRAFTINGSETTINGS_DYNAMICINPUT															250
#define IDD_DRAFTINGSETTINGS_QUICKPROPERTIES														260
#define IDD_DRAFTINGSETTINGS_SELECTIONCYCLING														270

#define IDD_DRAWINGUNITS																			300
#define IDD_DRAWINGWINDOWCOLOURS																	400

#define IDD_OPTIONS																					510
#define IDD_OPTIONS_FILES																			520
#define IDD_OPTIONS_DISPLAY																			530
#define IDD_OPTIONS_OPENANDSAVE																		540
#define IDD_OPTIONS_PLOTANDPUBLISH																	550
#define IDD_OPTIONS_SYSTEM																			560
#define IDD_OPTIONS_USERPREFERENCES																	570
#define IDD_OPTIONS_DRAFTING																		580
#define IDD_OPTIONS_3DMODELING																		590
#define IDD_OPTIONS_SELECTION																		591
#define IDD_OPTIONS_PROFILES																		592

#define IDD_UCS																						600
#define IDD_UCS_NAMEDUCS																			610
#define IDD_UCS_ORTHOGRAPHICUCS																		620
#define IDD_UCS_SETTINGS																			630

#define IDD_UCSICON																					700

#define IDD_VIEWMANAGER																				800

#define IDD_VIEWPORTS																				900
#define IDD_VIEWPORTS_NEW_VIEWPORTS																	910
#define IDD_VIEWPORTS_NAMED_VIEWPORTS																920

/////////////////////////////////////////////////////////////////////////////
//
// Controls
//

#define IDC_VIEW_VIEWPORTS_EDITTEXT_NEW_NAME														1140
#define IDC_VIEW_VIEWPORTS_LISTBOX_NEWVIEWPORTS														1150
#define IDC_VIEW_VIEWPORTS_GROUPBOX_PREVIEW															1160
#define IDC_VIEW_VIEWPORTS_LISTBOX_NAMEDVIEWPORTS													1170
#define IDC_VIEW_VIEWPORTS_COMBOBOX_CONTEXT															1180
#define IDC_VIEW_VIEWPORTS_COMBOBOX_SETUP															1190
#define IDC_VIEW_VIEWPORTS_COMBOBOX_VIEW															1200
#define IDC_VIEW_VIEWPORTS_COMBOBOX_VISUALSTYLE														1210

#define IDC_VIEW_VIEWMANAGER_LTEXT_CURRENTVIEW														1310
#define IDC_VIEW_VIEWMANAGER_GROUPBOX_VIEWS															1320
#define IDC_VIEW_VIEWMANAGER_TREEVIEW_VIEWS															1330
#define IDC_VIEW_VIEWMANAGER_EDIT																	1340
#define IDC_VIEW_VIEWMANAGER_BUTTON_APPLY															1350
#define IDC_VIEW_VIEWMANAGER_BUTTON_SETCURRENT														1360
#define IDC_VIEW_VIEWMANAGER_BUTTON_NEW																1370
#define IDC_VIEW_VIEWMANAGER_BUTTON_UPDATELAYERS													1380
#define IDC_VIEW_VIEWMANAGER_BUTTON_EDITBOUNDARIES													1390
#define IDC_VIEW_VIEWMANAGER_BUTTON_DELETE															1400

#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_GROUPBOX_STYLE											1500
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_RADIOBUTTON_2D											1510
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_RADIOBUTTON_3D											1520
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_LTEXT_LINEWIDTH											1530
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_COMBOBOX_LINEWIDTH										1540

#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_GROUPBOX_SIZE											1550
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_EDITTEXT_SIZE											1560
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_TRACKBAR_SIZE											1570

#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_GROUPBOX_PREVIEW										1570
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_GROUPBOX_COLOUR											1580
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_LTEXT_MODELSPACE_COLOUR									1590
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_COMBOBOX_MODELSPACEICONCOLOUR							1600
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_LTEXT_LAYOUTTAB_COLOUR									1610
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_COMBOBOX_LAYOUTTABICONCOLOUR							1620
#define IDC_VIEW_DISPLAY_UCSICON_PROPERTIES_CHECKBOX_SINGLECOLOUR									1630

#define IDC_FORMAT_DRAWINGUNITS_GROUPBOX_LENGTH														1631
#define IDC_FORMAT_DRAWINGUNITS_LTEXT_LENGTH_TYPE													1632
#define IDC_FORMAT_DRAWINGUNITS_COMBOBOX_LENGTH_TYPE												1633
#define IDC_FORMAT_DRAWINGUNITS_LTEXT_LENGTH_PRECISION												1634
#define IDC_FORMAT_DRAWINGUNITS_COMBOBOX_LENGTH_PRECISION											1635
#define IDC_FORMAT_DRAWINGUNITS_GROUPBOX_ANGLE														1636
#define IDC_FORMAT_DRAWINGUNITS_LTEXT_ANGLE_TYPE													1637
#define IDC_FORMAT_DRAWINGUNITS_COMBOBOX_ANGLE_TYPE													1638
#define IDC_FORMAT_DRAWINGUNITS_LTEXT_ANGLE_PRECISION												1639
#define IDC_FORMAT_DRAWINGUNITS_COMBOBOX_ANGLE_PRECISION											1640
#define IDC_FORMAT_DRAWINGUNITS_ANGLE_CHECKBOX_CLOCKWISE											1641
#define IDC_FORMAT_DRAWINGUNITS_GROUPBOX_INSERTIONSCALE												1642
#define IDC_FORMAT_DRAWINGUNITS_LTEXT_INSERTIONSCALE												1643
#define IDC_FORMAT_DRAWINGUNITS_COMBOBOX_INSERTIONSCALE												1644
#define IDC_FORMAT_DRAWINGUNITS_GROUPBOX_SAMPLEOUTPUT												1645
#define IDC_FORMAT_DRAWINGUNITS_SAMPLEOUTPUT_LTEXT_LENGTH											1646
#define IDC_FORMAT_DRAWINGUNITS_SAMPLEOUTPUT_LTEXT_ANGLE											1647
#define IDC_FORMAT_DRAWINGUNITS_GROUPBOX_LIGHTING													1648
#define IDC_FORMAT_DRAWINGUNITS_LTEXT_LIGHTING														1649
#define IDC_FORMAT_DRAWINGUNITS_COMBOBOX_LIGHTING													1650
#define IDC_DIRECTION																				1660

#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_ENABLEPOINTERINPUT									1661
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_ENABLEPOINTERINPUT_TOOLTIP							1662
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_ENABLEDIMENSIONINPUT								1663
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_ENABLEDIMENSIONINPUT_TOOLTIP						1664
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_GROUPBOX_POINTERINPUT								1665
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_POINTERINPUT_SETTINGS								1666
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_GROUPBOX_DIMENSIONINPUT								1667
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_DIMENSIONINPUT_SETTINGS								1668
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_GROUPBOX_DYNAMICPROMPTS								1669
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_SHOWINPUTNEARCROSSHAIRS								1670
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_SHOWINPUTNEARCROSSHAIRS_TOOLTIP						1671
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_SHOWADDITIONALTOOLTIPS								1672
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_SHOWADDITIONALTOOLTIPS_TOOLTIP						1673
#define IDC_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_DRAFTINGTOOLTIPAPPEARANCE							1674

#define IDC_TOOLS_OPTIONS_LTEXT_CURRENTPROFILE														1630
#define IDC_TOOLS_OPTIONS_LTEXT_CURRENTDRAWING														1640
#define IDC_TOOLS_OPTIONS_TABCONTROL																1650

#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_LTEXT_CONTEXT										1650
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_LISTBOX_CONTEXT										1655
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_LTEXT_INTERFACEELEMENT								1660
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_LISTBOX_INTERFACEELEMENT								1665
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_LTEXT_COLOUR											1670
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_COMBOBOX_COLOUR										1671
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_CHECKBOX_TINTFORXYZ									1672
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_BUTTON_RESTORECURRENTELEMENT							1673
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_BUTTON_RESTORECURRENTCONTEXT							1674
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_BUTTON_RESTOREALLCONTEXTS							1675
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_BUTTON_RESTORECLASSICCOLOURS							1676
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_LTEXT_PREVIEW										1680
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_CONTROL_PREVIEW_A									1690
#define IDC_TOOLS_OPTIONS_DRAWINGWINDOWCOLOURS_CONTROL_PREVIEW_B									1700

#define IDC_TOOLS_OPTIONS_DISPLAY_GROUPBOX_WINDOWELEMENTS											1650
#define IDC_TOOLS_OPTIONS_DISPLAY_LTEXT_COLOURTHEME													1660
#define IDC_TOOLS_OPTIONS_DISPLAY_COMBOBOX_COLOURTHEME												1670
#define IDC_TOOLS_OPTIONS_DISPLAY_CHECKBOX_DISPLAYSCROLLBARS										1680
#define IDC_TOOLS_OPTIONS_DISPLAY_CHECKBOX_WINDOWELEMENTS_LARGEBUTTONS								1681
#define IDC_TOOLS_OPTIONS_DISPLAY_CHECKBOX_WINDOWELEMENTS_RESIZERIBBONICONS							1682
#define IDC_TOOLS_OPTIONS_DISPLAY_CHECKBOX_WINDOWELEMENTS_SHOWTOOLTIPS								1683
#define IDC_TOOLS_OPTIONS_DISPLAY_EDITTEXT_WINDOWELEMENTS_NUMBEROFSECONDSBEFOREDISPLAY				1684
#define IDC_TOOLS_OPTIONS_DISPLAY_LTEXT_WINDOWELEMENTS_NUMBEROFSECONDSBEFOREDISPLAY					1685
#define IDC_TOOLS_OPTIONS_DISPLAY_CHECKBOX_SHOWSHORTCUTKEYSINTOOLTIPS								1686
#define IDC_TOOLS_OPTIONS_DISPLAY_CHECKBOX_SHOWEXTENDEDTOOLTIPS										1687
#define IDC_TOOLS_OPTIONS_OPENANDSAVE_GROUPBOX_FILESAVE												1690
#define IDC_TOOLS_OPTIONS_PLOTANDPUBLISH_GROUPBOX_DEFAULTPLOTSETTINGS								1700
#define IDC_TOOLS_OPTIONS_SYSTEM_GROUPBOX_HARDWAREACCELERATION										1710
#define IDC_TOOLS_OPTIONS_USERPREFERENCES_GROUPBOX_WINDOWSSTANDARDBEHAVIOUR							1720
#define IDC_TOOLS_OPTIONS_DRAFTING_GROUPBOX_AUTOSNAP_SETTINGS										1730
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_AUTOSNAP_SETTINGS_MARKER								1740
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_AUTOSNAP_SETTINGS_MAGNET								1750
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_AUTOSNAP_SETTINGS_DISPLAYAUTOSNAPTOOLTIP				1760
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_AUTOSNAP_SETTINGS_DISPLAYAUTOSNAPAPERTUREBOX			1770
#define IDC_TOOLS_OPTIONS_DRAFTING_BUTTON_AUTOSNAP_SETTINGS_COLOURS									1780
#define IDC_TOOLS_OPTIONS_DRAFTING_GROUPBOX_AUTOTRACK_SETTINGS										1790
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_AUTOTRACK_SETTINGS_DISPLAYPOLARTRACKINGVECTOR			1800
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_AUTOTRACK_SETTINGS_DISPLAYFULLSCREENTRACKINGVECTOR		1810
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_AUTOTRACK_SETTINGS_DISPLAYAUTOTRACKTOOLTIP				1820
#define IDC_TOOLS_OPTIONS_DRAFTING_GROUPBOX_ALIGNMENT_POINTACQUISITION								1830
#define IDC_TOOLS_OPTIONS_DRAFTING_RADIOBUTTON_ALIGNMENT_POINTACQUISITION_AUTOMATIC					1840
#define IDC_TOOLS_OPTIONS_DRAFTING_RADIOBUTTON_ALIGNMENT_POINTACQUISITION_SHIFTTOACQUIRE			1850
#define IDC_TOOLS_OPTIONS_DRAFTING_GROUPBOX_AUTOSNAP_MARKER_SIZE									1860
#define IDC_TOOLS_OPTIONS_DRAFTING_CONTROL_AUTOSNAP_MARKER_SIZE										1870
#define IDC_TOOLS_OPTIONS_DRAFTING_TRACKBAR_AUTOSNAP_MARKER_SIZE									1875
#define IDC_TOOLS_OPTIONS_DRAFTING_GROUPBOX_APERTURE_SIZE											1880
#define IDC_TOOLS_OPTIONS_DRAFTING_CONTROL_APERTURE_SIZE											1890
#define IDC_TOOLS_OPTIONS_DRAFTING_TRACKKBAR_APERTURE_SIZE											1895
#define IDC_TOOLS_OPTIONS_DRAFTING_GROUPBOX_OBJECTSNAPOPTIONS										1900
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_OBJECTSNAPOPTIONS_HATCH									1910
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_OBJECTSNAPOPTIONS_EXTENSION								1920
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_OBJECTSNAPOPTIONS_ZOBJECT								1930
#define IDC_TOOLS_OPTIONS_DRAFTING_CHECKBOX_OBJECTSNAPOPTIONS_ZVALUE								1940
#define IDC_TOOLS_OPTIONS_DRAFTING_BUTTON_OBJECTSNAPOPTIONS_DRAFTINGTOOLTIPSETTINGS					1950
#define IDC_TOOLS_OPTIONS_DRAFTING_BUTTON_OBJECTSNAPOPTIONS_LIGHTSGLYPHSETTINGS						1960
#define IDC_TOOLS_OPTIONS_DRAFTING_BUTTON_OBJECTSNAPOPTIONS_CAMERASGLYPHSETTINGS					1970
#define IDC_TOOLS_OPTIONS_3DMODELING_GROUPBOX_3DCROSSHAIRS											1980
#define IDC_TOOLS_OPTIONS_SELECTION_GROUPBOX_PICKBOXSIZE											1990

#define IDC_TOOLS_OPTIONS_APPLY																		2000

/////////////////////////////////////////////////////////////////////////////
//
// String Tables
//

#define ID_VIEWPORTS_CLASS																			130
#define ID_VIEWPORTS_NAME																			131
#define ID_VIEWMANAGER_CLASS																		132
#define ID_VIEWMANAGER_NAME																			133
#define ID_UCSICONPROPERTIES_CLASS																	134
#define ID_DRAWINGUNITS_CLASS																		135
#define ID_UCS_CLASS																				136
#define ID_DRAFTINGSETTINGS_CLASS																	137
#define ID_DRAFTINGSETTINGS_NAME																	138
#define ID_DRAWINGWINDOWCOLOURS_CLASS																139
#define ID_OPTIONS_CLASS																			140

#define ID_VIEW_CURRENT																				2200
#define ID_TOP																						2210
#define ID_BOTTOM																					2220
#define ID_LEFT																						2230
#define ID_RIGHT																					2240
#define ID_FRONT																					2250
#define ID_BACK																						2260
#define ID_SWISOMETRIC																				2270
#define ID_SEISOMETRIC																				2280
#define ID_NEISOMETRIC																				2290
#define ID_NWISOMETRIC																				2300

#define ID_CURRENT																					2400
#define ID_2DWIREFRAME																				2405
#define ID_3DWIREFRAME																				2410
#define ID_HIDDEN																					2420
#define ID_3DHIDDEN																					2430
#define ID_CONCEPTUAL																				2440
#define ID_REALISTIC																				2450
#define ID_SHADED																					2460
#define ID_SHADEDWITHEDGES																			2470
#define ID_SHADESOFGREY																				2480
#define ID_SKETCHY																					2490
#define ID_WIREFRAME																				2500
#define ID_XRAY																						2510

#define ID_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_ENABLEPOINTERINPUT_TOOLTIP							2520
#define ID_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_ENABLEDIMENSIONINPUT_TOOLTIP							2530
#define ID_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_SHOWINPUTNEARCROSSHAIRS_TOOLTIP						2540
#define ID_TOOLS_DRAFTINGSETTINGS_DYNAMICINPUT_SHOWADDITIONALTOOLTIPS_TOOLTIP						2550

#ifndef IDC_STATIC
#define IDC_STATIC																					-1
#endif

//Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC																					130
#define _APS_NEXT_RESOURCE_VALUE																	129
#define _APS_NEXT_COMMAND_VALUE																		32771
#define _APS_NEXT_CONTROL_VALUE																		1000
#define _APS_NEXT_SYMED_VALUE																		110
#endif
#endif
